/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/comer/interfaces/impl"
)

var Event *EventRepo

type EventRepo struct {
	impl.Repo
}

func NewEventRepo() {
	db:=global.MysqlDb
	Event = &EventRepo{
		Repo: *impl.NewRepo(db),
	}
}

func init() {
	RegisterRepos(NewEventRepo)
}
