/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package event

import (
	"github.com/gin-gonic/gin"
	_ "github.com/imoowi/live-stream-server/apps/event/migrates"
	"github.com/imoowi/live-stream-server/middlewares"
	"github.com/imoowi/live-stream-server/apps/event/handlers"
	"github.com/imoowi/live-stream-server/router"
)

func init() {
	router.RegisterRoute(Routers)
}

func Routers(e *gin.Engine) {
	api := e.Group("/api")
	api.Use(middlewares.JWTAuthMiddleware())
	api.Use(middlewares.CasbinMiddleware())
	api.Use(middlewares.UserLogMiddleware())
	events := api.Group("/events")
	{
		events.GET("", handlers.EventPageList) //分页
		events.GET("/:id", handlers.EventOne) //一个
		events.POST("", handlers.EventAdd) //新增
		events.PUT("/:id", handlers.EventUpdate) //更新
		events.PATCH("/:id", handlers.EventPatch) //部分更新
		events.DELETE("/:id", handlers.EventDel) //默认为软删除
	}

	srshooks := api.Group("/srshooks")
	{
		srshooks.GET("",handlers.SrshookPageList) //分页列表
		srshooks.GET("/:id",handlers.SrshookOne) //详情
		srshooks.POST("",handlers.SrshookAdd) //新增
		srshooks.PUT("/:id",handlers.SrshookUpdate) //更新
		srshooks.PATCH("/:id",handlers.SrshookPatch) //部分更新
		srshooks.DELETE("/:id",handlers.SrshookDel) //删除，默认为软删除
	}
	//!important:do-not-delete-this-line,不要删除此行，主要用于代码生成器
}
