/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package models

import (
	"github.com/imoowi/comer/components"
)

type EventBase struct{
	Name  string     `json:"name" form:"name" gorm:"column:name;type:varchar(30);not null;comment:名" `
}

// Event表
type Event struct {
	components.GormModel
	EventBase
}

// IModel.GetID实现
func (m *Event) GetID() uint {
	return m.ID
}
func (m *Event) SetId(id uint) {
	m.ID = id
}

// IModel.TableName实现
func (m *Event) TableName() string {
	return `event` + `s`
}
