/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package models

import (
	"github.com/imoowi/comer/components"
	"github.com/imoowi/comer/utils/request"
)

type EventBase struct {
	Name string `gorm:"column:name;type:varchar(30);not null;comment:名称"`
}

// Event表
type Event struct {
	components.GormModel
	EventBase
}

//新增
type EventAdd struct {
	EventBase
}

//完全更新
type EventUpdate struct {
	EventBase
}

//部分更新
type EventPatchUpdate struct {
	Name string `json:"name" form:"name"` //名称
}

//查询model
type EventQuery struct {
	request.PageList
	Key string `json:"key" form:"key"`
}