/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package models

import (
	"github.com/imoowi/comer/components"
	"github.com/imoowi/comer/utils/request"
)

type SrshookBase struct {
	Name string `gorm:"column:name;type:varchar(30);not null;comment:名称"`
}

// Srshook表
type Srshook struct {
	components.GormModel
	SrshookBase
}

//新增
type SrshookAdd struct {
	SrshookBase
}

//完全更新
type SrshookUpdate struct {
	SrshookBase
}

//部分更新
type SrshookPatchUpdate struct {
	Name string `json:"name" form:"name"` //名称
}

//查询model
type SrshookQuery struct {
	request.PageList
	Key string `json:"key" form:"key"`
}