/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package services

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/live-stream-server/internal/repos"
)

var SrsHook *SrsHookService

type SrsHookService struct {
	impl.Service[*models.SrsHook]
}

func NewSrsHookService(r *repos.SrsHookRepo) *SrsHookService {
	return &SrsHookService{
		Service: *impl.NewService[*models.SrsHook](r),
	}
}

func init() {
	RegisterServices(func() {
		SrsHook = NewSrsHookService(repos.SrsHook)
	})
}
