/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package apps

import (
	_ "github.com/imoowi/live-stream-server/apps/event"
	_ "github.com/imoowi/live-stream-server/apps/common"
	_ "github.com/imoowi/live-stream-server/apps/swagger"
	_ "github.com/imoowi/live-stream-server/apps/user"
)
