/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"errors"

	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/apps/event/models"
	"github.com/imoowi/comer/components"
	"github.com/imoowi/live-stream-server/global"
	"github.com/imoowi/comer/utils/response"
	"gorm.io/gorm"
)

type SrshookRepo struct {
	Db *components.MysqlODM
}

func newSrshookRepo() *SrshookRepo {
	return &SrshookRepo{
		Db: global.MysqlDb,
	}
}
func init() {
	global.DigContainer.Provide(newSrshookRepo)
}


func (r *SrshookRepo) All(c *gin.Context, query *models.SrshookQuery) (res []*models.Srshook, err error) {
	db := r.Db.Client
	if query.Key != `` {
		db = db.Where("`key`=?", query.Key)
	}

	err = db.Find(&res).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		err = nil
	}
	return
}

func (r *SrshookRepo) PageList(c *gin.Context, query *models.SrshookQuery) (res *response.PageList, err error) {
	db := r.Db.Client
	var users []*models.Srshook

	if query.SearchKey != `` {
		db = db.Where(`name LIKE ?`, `%`+query.SearchKey+`%`)
	}
	offset := (query.Page - 1) * query.PageSize
	db = db.Offset(int(offset)).Limit(int(query.PageSize))
	// db=db.Order(`name desc`)
	err = db.Find(&users).Error

	var count int64
	db.Offset(-1).Limit(-1).Count(&count)

	res = &response.PageList{
		List:  users,
		Pages: response.MakePages(count, query.Page, query.PageSize),
	}
	return
}

func (r *SrshookRepo) One(c *gin.Context, id uint) (user *models.Srshook, err error) {
	db := r.Db.Client
	err = db.Where(`id=?`, id).First(&user).Error
	return
}

func (r *SrshookRepo) OneByName(c *gin.Context, name string) (user *models.Srshook, err error) {
	db := r.Db.Client
	err = db.Where(`name=?`, name).First(&user).Error
	return
}
func (r *SrshookRepo) Add(c *gin.Context, model *models.Srshook) (newId uint, err error) {
	db := r.Db.Client
	db = db.Create(&model)
	err = db.Error

	newId =  model.ID
	return
}

func (r *SrshookRepo) Update(c *gin.Context, model *models.Srshook, id uint) (updated bool, err error) {
	if id == 0 {
		updated = false
		err = errors.New(`pls input id`)
		return
	}
	model.ID = uint(id)
	db := r.Db.Client
	err = db.Omit(`created_at`).Save(&model).Error
	if err == nil {
		updated = true
	}
	return
}

func (r *SrshookRepo) Delete(c *gin.Context, id uint) (deleted bool, err error) {
	if id == 0 {
		deleted = false
		err = errors.New(`pls input id`)
		return
	}
	db := r.Db.Client
	model, err := r.One(c, id)
	if err != nil {
		return
	}
	if model.ID == 0 {
		err = errors.New(`obj not exist`)
		return
	}
	err = db.Delete(&model).Error
	if err == nil {
		deleted = true
	}
	return
}
